-- Create ea_tasks_done table for tracking completions and extensions
CREATE TABLE IF NOT EXISTS public.ea_tasks_done (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT REFERENCES public.ea_tasks(task_id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    remarks TEXT,
    image_url TEXT,
    given_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_ea_tasks_done_task_id ON public.ea_tasks_done(task_id);
CREATE INDEX IF NOT EXISTS idx_ea_tasks_done_status ON public.ea_tasks_done(status);

-- Enable RLS
ALTER TABLE public.ea_tasks_done ENABLE ROW LEVEL SECURITY;

-- Simple policy for authenticated users (adjust as needed)
CREATE POLICY "Allow all for authenticated" ON public.ea_tasks_done
    FOR ALL USING (auth.role() = 'authenticated');
