-- 1. Create specific tables for Departments and Assign From (if they don't exist)
CREATE TABLE IF NOT EXISTS departments (
    id bigint generated by default as identity primary key,
    name text unique not null
);

CREATE TABLE IF NOT EXISTS assign_from (
    id bigint generated by default as identity primary key,
    name text unique not null
);

-- 2. Create the main 'dropdown' table with columns for each category
-- This replaces the generic 'dropdown_options' structure
CREATE TABLE IF NOT EXISTS dropdown (
    id bigint generated by default as identity primary key,
    task_priority text,
    project_type text,
    leave_type text,
    expense_category text,
    meeting_type text,
    machine_name text -- Added based on previous request for machines
);

-- 3. Insert Data into Departments
INSERT INTO departments (name) VALUES 
('Human Resources'), ('IT Department'), ('Marketing'), ('Sales'), 
('Operations'), ('Finance'), ('Legal'), ('Customer Support')
ON CONFLICT (name) DO NOTHING;

-- 4. Insert Data into Assign From
INSERT INTO assign_from (name) VALUES 
('CEO'), ('Director'), ('General Manager'), ('Department Head'), 
('Team Lead'), ('Project Manager'), ('Self')
ON CONFLICT (name) DO NOTHING;

-- 5. Insert Data into the pivoted 'dropdown' table
-- We insert rows where each column gets its respective value from the list 
-- Row 1
INSERT INTO dropdown (task_priority, project_type, leave_type, expense_category, meeting_type)
VALUES ('Urgent', 'Internal', 'Sick Leave', 'Travel', 'Daily Standup');

-- Row 2
INSERT INTO dropdown (task_priority, project_type, leave_type, expense_category, meeting_type)
VALUES ('High', 'Client', 'Casual Leave', 'Food & Beverages', 'Weekly Review');

-- Row 3
INSERT INTO dropdown (task_priority, project_type, leave_type, expense_category, meeting_type)
VALUES ('Medium', 'Research', 'Earned Leave', 'Accommodation', 'Monthly Planning');

-- Row 4
INSERT INTO dropdown (task_priority, project_type, leave_type, expense_category, meeting_type)
VALUES ('Low', NULL, 'Work From Home', 'Office Supplies', 'Client Call');

-- 6. Insert Users (Sample Data)
CREATE TYPE user_status AS ENUM ('active', 'inactive', 'on_leave');
-- (If type already exists, this might error, but in a script we'd check existence. 
-- For now we assume standard setup or ignore if exists).



INSERT INTO users (user_name, email_id, password, number, employee_id, role, status, user_access) 
VALUES 
('Admin User', 'admin@botivate.com', 'password123', '9876543210', 'EMP001', 'admin', 'active', 'IT Department'),
('John Manager', 'john@botivate.com', 'password123', '9876543211', 'EMP002', 'manager', 'active', 'Sales'),
('Sarah Director', 'sarah@botivate.com', 'password123', '9876543212', 'EMP003', 'manager', 'active', 'Marketing'),
('Mike Developer', 'mike@botivate.com', 'password123', '9876543213', 'EMP004', 'user', 'active', 'IT Department'),
('Emily Sales', 'emily@botivate.com', 'password123', '9876543214', 'EMP005', 'user', 'active', 'Sales'),
('David Ops', 'david@botivate.com', 'password123', '9876543215', 'EMP006', 'user', 'active', 'Operations'),
('Jessica HR', 'jessica@botivate.com', 'password123', '9876543216', 'EMP007', 'user', 'on_leave', 'Human Resources')
ON CONFLICT (email_id) DO NOTHING;
